#
# Your Crowdin credentials
#
project_id: "719001"
api_token_env: CROWDIN_API_KEY
base_path: "."
base_url: "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
  {
    "source": "xaero-map-chinese/en_us/xaero-betterpvp.json",
    "translation": "xaero-map-chinese/%locale%/xaero-betterpvp.json",
  },
  {
    "source": "xaero-map-chinese/en_us/xaero-minimap.json",
    "translation": "xaero-map-chinese/%locale%/xaero-minimap.json",
  },
  {
    "source": "xaero-map-chinese/en_us/xaero-worldmap.json",
    "translation": "xaero-map-chinese/%locale%/xaero-worldmap.json",
  }
]